### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by shenglinchuan** [Peterclark1996/s2ts#2]
![796768bd936533149019c6f1ce6f6026](https://github.com/user-attachments/assets/3a86f5db-f21d-4c5b-9fbb-0beb14062a6b)

nodejs: v20.18.0
windows 11 23H2

The prev version can run normally
but the version with vmap added is not working

**Comment by Peterclark1996** [comment]
Thanks for raising. I'm also on node v20.18.0 and windows 11 23H2 but can't recreate this issue.
Would you be able to try run `npx create-s2ts@latest` to make sure npx is fetching the latest version and its not a cache issue?

**Comment by shenglinchuan** [comment]
> Thanks for raising. I'm also on node v20.18.0 and windows 11 23H2 but can't recreate this issue. Would you be able to try run `npx create-s2ts@latest` to make sure npx is fetching the latest version and its not a cache issue?

I have tried using it this way, but the problem still persists.
and i try `npm cache clean --force`

Maybe it's because I use a mobile network?

**Comment by Peterclark1996** [comment]
I've just pushed another patch version to remove the need for `copyFileSync`. Trying `npx create-s2ts@latest` again might work now

**Comment by Peterclark1996** [comment]
Gonna close for now but please open again if you still have any issues
